version: '3'
services:
  # Servicio de MySQL
  mysql: #nombre sel servicio
    image: mysql:8.0   # especificamos la image  del docker que se va a utilizar
    container_name: mi_mysql #definimos el nombre del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: 2103  #le establesemos la contraseña del usuario root del de MYSQL   
    volumes: 
      - mysql_data:/var/lib/mysql
    ports: # mapeo el puerto del contenedor al puerto del host
      - "3306:3306" 
    networks: #especifica a que redes docker se debe conectar el contenedor
      - my_network


volumes: #definimos el volumes para que los datos de MYSQL persitan fuera del contenedor y tambien se utilizara en la app
  mysql_data:

networks: #definimos las redes que se utilizaran en la APP para conectar diferentes contenedores si y/o con el host
  my_network: